name = "TaCZ Pack"
author = "Xander"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a08d74d91524112a0dc5622ee69703577be71fd811bacc8c0ef0c4385a1f5361"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.89"
