name = "TaCZ Pack"
author = "Xander"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd32ff5554ef462ee0bdc93f0043c72b3d0c6860a2e3a141f3fa73d320a665f1"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.89"
