name = "TaCZ Pack"
author = "Xander"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a02da029a1be9722ebc71e86c8843391f0d4592dd36e78e5504fe30d80747598"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.89"
